### ISSUE TITLE
Zenity windows stay open in non-responsive state for duration of python script

### ISSUE THREAD

**Issue by jonwedell** [poulp/python-zenity#10]
On Ubuntu 15.10 zenity windows created during python scripts using the library do not close until the entire program has finished running rather than when the window is done. For example, if you run the code below the zenity message box does not dissapear until after 100 seconds (though the result and control is returned when the user presses enter):

#!/usr/bin/python

import pythonzenity
import time
a = pythonzenity.Message(text="Message in the bottle")
time.sleep(100)

**Comment by poulp** [comment]
https://github.com/poulp/python-zenity/commit/71f9afe1118e7878ba8eb35f5d6736794ca6bae6

This should resolve the issue, ty for the feedback ;)

**Comment by jonwedell** [comment]
Great, that fixed it. Thanks!
